
name: Submodule a1policymanagementservice CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
        
    - name: Build a1policymanagementservice Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd a1policymanagementservice
        ls -la
        mvn clean install -Dmaven.test.skip=true
        docker build -t o-ran-sc/a1policymanagementservice .
        
    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Docker Login
      run: |
        echo "${{ secrets.GHCR }}" | docker login ghcr.io -u sknrao --password-stdin

    - name: Tag & Push Docker Images
      run: |
        docker tag o-ran-sc/a1policymanagementservice:latest ghcr.io/sknrao/a1policymanagementservice:latest
        docker push ghcr.io/sknrao/a1policymanagementservice:latest