
name: Submodule atoken CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    - name: Build atoken Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd atoken
        ls -la
        cd auth-token-fetch
        ls -la
        docker build -t sknrao/nonrtric-plt-auth-token-fetch .
        docker tag sknrao/nonrtric-plt-auth-token-fetch ghcr.io/sknrao/nonrtric-plt-auth-token-fetch
      # docker push ghcr.io/sknrao/nonrtric-plt-auth-token-fetch
      
    - name: Show The Build Docker Images
      run: |
        docker images
      
