name: Submodule cp-gw CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    - name: Build cp-gw Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd cp-gw
        ls -la
        cd nonrtric-gateway
        ls -la
        mvn clean install
      # mvn install docker:build
        

    - name: Build cp-gw Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd cp-gw
        ls -la
        cd webapp-frontend
        ls -la
        mvn clean install
        mvn install docker:build

    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Docker Login
      run: |
        echo "${{ secrets.GHCR }}" | docker login ghcr.io -u sknrao --password-stdin

    - name: Tag & Push Docker Images
      run: |
        docker tag o-ran-sc/nonrtric-plt-informationcoordinatorservice:latest ghcr.io/sknrao/nonrtric-plt-informationcoordinatorservice:latest
        docker tag o-ran-sc/nonrtric-plt-informationcoordinatorservice:2.5.0-SNAPSHOT ghcr.io/sknrao/nonrtric-plt-informationcoordinatorservice:2.5.0
        docker push ghcr.io/sknrao/nonrtric-plt-informationcoordinatorservice:latest
        docker push ghcr.io/sknrao/nonrtric-plt-informationcoordinatorservice:2.5.0
