name: Submodule cp-gw CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    - name: Build cp-gw Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd cp-gw
        ls -la
        cd nonrtric-gateway
        ls -la
        mvn clean install
        docker images

    - name: Build cp-gw Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd cp-gw
        ls -la
        cd webapp-frontend
        ls -la
        mvn clean install
        mvn install docker:build
        docker images
        docker tag o-ran-sc/nonrtric-controlpanel:latest ghcr.io/sknrao/nonrtric-controlpanel:latest
      # docker tag ios-mcn-smo/nonrtric-controlpanel:latest ghcr.io/ios-mcn-smo/nonrtric-controlpanel:latest
      # docker push ghcr.io/ios-mcn-smo/nonrtric-gateway:latest
    - name: Show The Build Docker Images
      run: |
        docker images
