name: Submodule ics CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install xmlstarlet
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la

    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    # - name: Build
    #   run: |
    #     ls -la
    #     cd deps/ics
    #     ls -la
    #     mvn clean install
    #     mvn install docker:build
    #     docker images
    #     docker tag o-ran-sc/nonrtric-plt-informationcoordinatorservice:latest ghcr.io/sknrao/nonrtric-plt-informationcoordinatorservice:latest
      # docker tag ios-mcn-smo/nonrtric-plt-informationcoordinatorservice:latest ghcr.io/ios-mcn-smo/nonrtric-plt-informationcoordinatorservice:latest


    - name: Build
      run: |
        ls -la
        cd deps
        ls -la
        # cd atoken/auth-token-fetch
        # docker build -t sknrao/nonrtric-plt-auth-token-fetch .
        # docker tag sknrao/nonrtric-plt-auth-token-fetch ghcr.io/sknrao/nonrtric-plt-auth-token-fetch
