name: Submodule sdnc-oam CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install xmlstarlet
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    - name: Build
      run: |
        ls -la
        cd deps
        ls -la
        cd sdnc-oam
        ls -la
        mvn clean install -P docker -Ddocker.pull.registry=nexus3.onap.org:10001
        ls -la
        docker images
        docker tag onap/sdnc-image:2.6.1-SNAPSHOT-latest ghcr.io/ios-mcn-smo/sdnc-image:2.6.1-SNAPSHOT-latest
        docker tag onap/sdnc-web-image:2.6.1-SNAPSHOT-latest ghcr.io/ios-mcn-smo/sdnc-web-image:2.6.1-SNAPSHOT-latest
    #     cp ./src/docker/Dockerfile ./target/VESCollector-1.12.3-SNAPSHOT/
    #     cd ./target/VESCollector-1.12.3-SNAPSHOT/
    #     docker build -t ios-mcn-smo/ves-collector:1.12.3 .
    # - name: Build
    #   run: |
    #     docker images
