name: Submodule Changes CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install xmlstarlet
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Install xmlstarlet
      run: |
        sudo apt install xmlstarlet -y
        
    - name: Build
      run: |
        ls -la
        cd deps/ves-collector
        ls -la
        mvn clean package
    #     # cd src/docker
    #     # ls -la
    #     # docker build -t ios-mcn-smo/ves-collector:1.12.3 .
